### ISSUE TITLE
Set encodings and charsets properly (watch for PHPMailer defaults)

### ISSUE THREAD

**Issue by haelge** [dschmidt/billo#6]
If I send an email in plaintext from rainloop (webailer) e.g. the content is transfer-encoded "quoted-printable".
If that mail is forwarded to the listmembers the encoding changes to 8bit, therefore the qp-escape symbols appear as characters.

Maybe we have to take the given transfer-encoding into account to force it in the further delivery?

What happens is:
The message

> 1
> 2
> ü
> ß

becomes 

> =0A1=0A2=0A=C3=BC=0A=C3=9F

**Comment by haelge** [comment]
You have to write these things down to get an overview ;) 

It is possible to force a transfer-encoding by setting e.g. 
`$mailSender->Encoding = 'quoted-printable'`

Now the plaintext mail is rendered correct but the german special character are still broken. 

> 1
> 2
> Ã¼
> Ã


Most likely because the charset in Content-Type ist somehow "double defined" 

`Content-Type: text/plain;
 charset="utf-8"; charset=iso-8859-1`

**Comment by dschmidt** [comment]
We should probably make sure to copy as much from the original mail as possible by replacing most of the logic in PHPMailer. I've used it because it seems to have a solid SMTP implementation (supporting STARTTLS). But we don't need most of the creation api as we are only forwarding mails.

P.S.: There's `PHPMailer::ENCODING_QUOTED_PRINTABLE` which is defined as the string you used.

**Comment by haelge** [comment]
And now I am a suspected spamer XD. I couldn't double check it but I found the folowing issues:

`$mailSender->ContentType = $message->ContentType;` 
sets the ContentType to 'text/plain' and injects charset="utf-8". But PHPMailer doesn't recognize the charset and sets it's default 'iso-8859-1'. Since there is no setting for the transfer-encoding it again sets it's default '8bit'.

If we extract these properties correctly and set them properly we should be good to go with PHPMailer.

**Comment by dschmidt** [comment]
Ah, very interesting.

https://github.com/PHPMailer/PHPMailer/blob/c2796cb1cb99d7717290b48c4e6f32cb6c60b7b3/src/PHPMailer.php#L2468

We can probably just override this function to return the original headers. Analogously to the createBody() override :)

**Comment by haelge** [comment]
Beacause i had comprehended your annotation at first sight and with no need of continuous clarification, especially not via whatsapp or after midnight, i managed to do so.

**Comment by dschmidt** [comment]
This was fixed in #7 right?

**Comment by haelge** [comment]
Ah sorry, yes. I lost track in this topic 😅
